#ifndef RAYBASE_MACRO_HACKS_HH
#define RAYBASE_MACRO_HACKS_HH

namespace rb
{
#define RB_FOREACH_0(WHAT)
#define RB_FOREACH_1(WHAT, X) WHAT(X)
#define RB_FOREACH_2(WHAT, X, ...) WHAT(X)RB_FOREACH_1(WHAT, __VA_ARGS__)
#define RB_FOREACH_3(WHAT, X, ...) WHAT(X)RB_FOREACH_2(WHAT, __VA_ARGS__)
#define RB_FOREACH_4(WHAT, X, ...) WHAT(X)RB_FOREACH_3(WHAT, __VA_ARGS__)
#define RB_FOREACH_5(WHAT, X, ...) WHAT(X)RB_FOREACH_4(WHAT, __VA_ARGS__)
#define RB_FOREACH_6(WHAT, X, ...) WHAT(X)RB_FOREACH_5(WHAT, __VA_ARGS__)
#define RB_FOREACH_7(WHAT, X, ...) WHAT(X)RB_FOREACH_6(WHAT, __VA_ARGS__)
#define RB_FOREACH_8(WHAT, X, ...) WHAT(X)RB_FOREACH_7(WHAT, __VA_ARGS__)
#define RB_FOREACH_9(WHAT, X, ...) WHAT(X)RB_FOREACH_8(WHAT, __VA_ARGS__)
#define RB_FOREACH_10(WHAT, X, ...) WHAT(X)RB_FOREACH_9(WHAT, __VA_ARGS__)
#define RB_FOREACH_11(WHAT, X, ...) WHAT(X)RB_FOREACH_10(WHAT, __VA_ARGS__)
#define RB_FOREACH_12(WHAT, X, ...) WHAT(X)RB_FOREACH_11(WHAT, __VA_ARGS__)
#define RB_FOREACH_13(WHAT, X, ...) WHAT(X)RB_FOREACH_12(WHAT, __VA_ARGS__)
#define RB_FOREACH_14(WHAT, X, ...) WHAT(X)RB_FOREACH_13(WHAT, __VA_ARGS__)
#define RB_FOREACH_15(WHAT, X, ...) WHAT(X)RB_FOREACH_14(WHAT, __VA_ARGS__)
#define RB_FOREACH_16(WHAT, X, ...) WHAT(X)RB_FOREACH_15(WHAT, __VA_ARGS__)
#define RB_FOREACH_17(WHAT, X, ...) WHAT(X)RB_FOREACH_16(WHAT, __VA_ARGS__)
#define RB_FOREACH_18(WHAT, X, ...) WHAT(X)RB_FOREACH_17(WHAT, __VA_ARGS__)
#define RB_FOREACH_19(WHAT, X, ...) WHAT(X)RB_FOREACH_18(WHAT, __VA_ARGS__)
#define RB_FOREACH_20(WHAT, X, ...) WHAT(X)RB_FOREACH_19(WHAT, __VA_ARGS__)
#define RB_FOREACH_21(WHAT, X, ...) WHAT(X)RB_FOREACH_20(WHAT, __VA_ARGS__)
#define RB_FOREACH_22(WHAT, X, ...) WHAT(X)RB_FOREACH_21(WHAT, __VA_ARGS__)
#define RB_FOREACH_23(WHAT, X, ...) WHAT(X)RB_FOREACH_22(WHAT, __VA_ARGS__)
#define RB_FOREACH_24(WHAT, X, ...) WHAT(X)RB_FOREACH_23(WHAT, __VA_ARGS__)
#define RB_FOREACH_25(WHAT, X, ...) WHAT(X)RB_FOREACH_24(WHAT, __VA_ARGS__)
#define RB_FOREACH_26(WHAT, X, ...) WHAT(X)RB_FOREACH_25(WHAT, __VA_ARGS__)
#define RB_FOREACH_27(WHAT, X, ...) WHAT(X)RB_FOREACH_26(WHAT, __VA_ARGS__)
#define RB_FOREACH_28(WHAT, X, ...) WHAT(X)RB_FOREACH_27(WHAT, __VA_ARGS__)
#define RB_FOREACH_29(WHAT, X, ...) WHAT(X)RB_FOREACH_28(WHAT, __VA_ARGS__)
#define RB_FOREACH_30(WHAT, X, ...) WHAT(X)RB_FOREACH_29(WHAT, __VA_ARGS__)
#define RB_FOREACH_31(WHAT, X, ...) WHAT(X)RB_FOREACH_30(WHAT, __VA_ARGS__)
#define RB_FOREACH_32(WHAT, X, ...) WHAT(X)RB_FOREACH_31(WHAT, __VA_ARGS__)
#define RB_FOREACH_33(WHAT, X, ...) WHAT(X)RB_FOREACH_32(WHAT, __VA_ARGS__)
#define RB_FOREACH_34(WHAT, X, ...) WHAT(X)RB_FOREACH_33(WHAT, __VA_ARGS__)
#define RB_FOREACH_35(WHAT, X, ...) WHAT(X)RB_FOREACH_34(WHAT, __VA_ARGS__)
#define RB_FOREACH_36(WHAT, X, ...) WHAT(X)RB_FOREACH_35(WHAT, __VA_ARGS__)
#define RB_FOREACH_37(WHAT, X, ...) WHAT(X)RB_FOREACH_36(WHAT, __VA_ARGS__)
#define RB_FOREACH_38(WHAT, X, ...) WHAT(X)RB_FOREACH_37(WHAT, __VA_ARGS__)
#define RB_FOREACH_39(WHAT, X, ...) WHAT(X)RB_FOREACH_38(WHAT, __VA_ARGS__)
#define RB_FOREACH_40(WHAT, X, ...) WHAT(X)RB_FOREACH_39(WHAT, __VA_ARGS__)
#define RB_FOREACH_41(WHAT, X, ...) WHAT(X)RB_FOREACH_40(WHAT, __VA_ARGS__)
#define RB_FOREACH_42(WHAT, X, ...) WHAT(X)RB_FOREACH_41(WHAT, __VA_ARGS__)
#define RB_FOREACH_43(WHAT, X, ...) WHAT(X)RB_FOREACH_42(WHAT, __VA_ARGS__)
#define RB_FOREACH_44(WHAT, X, ...) WHAT(X)RB_FOREACH_43(WHAT, __VA_ARGS__)
#define RB_FOREACH_45(WHAT, X, ...) WHAT(X)RB_FOREACH_44(WHAT, __VA_ARGS__)
#define RB_FOREACH_46(WHAT, X, ...) WHAT(X)RB_FOREACH_45(WHAT, __VA_ARGS__)
#define RB_FOREACH_47(WHAT, X, ...) WHAT(X)RB_FOREACH_46(WHAT, __VA_ARGS__)
#define RB_FOREACH_48(WHAT, X, ...) WHAT(X)RB_FOREACH_47(WHAT, __VA_ARGS__)
#define RB_FOREACH_49(WHAT, X, ...) WHAT(X)RB_FOREACH_48(WHAT, __VA_ARGS__)
#define RB_FOREACH_50(WHAT, X, ...) WHAT(X)RB_FOREACH_49(WHAT, __VA_ARGS__)
#define RB_FOREACH_51(WHAT, X, ...) WHAT(X)RB_FOREACH_50(WHAT, __VA_ARGS__)
#define RB_FOREACH_52(WHAT, X, ...) WHAT(X)RB_FOREACH_51(WHAT, __VA_ARGS__)
#define RB_FOREACH_53(WHAT, X, ...) WHAT(X)RB_FOREACH_52(WHAT, __VA_ARGS__)
#define RB_FOREACH_54(WHAT, X, ...) WHAT(X)RB_FOREACH_53(WHAT, __VA_ARGS__)
#define RB_FOREACH_55(WHAT, X, ...) WHAT(X)RB_FOREACH_54(WHAT, __VA_ARGS__)
#define RB_FOREACH_56(WHAT, X, ...) WHAT(X)RB_FOREACH_55(WHAT, __VA_ARGS__)
#define RB_FOREACH_57(WHAT, X, ...) WHAT(X)RB_FOREACH_56(WHAT, __VA_ARGS__)
#define RB_FOREACH_58(WHAT, X, ...) WHAT(X)RB_FOREACH_57(WHAT, __VA_ARGS__)
#define RB_FOREACH_59(WHAT, X, ...) WHAT(X)RB_FOREACH_58(WHAT, __VA_ARGS__)
#define RB_FOREACH_60(WHAT, X, ...) WHAT(X)RB_FOREACH_59(WHAT, __VA_ARGS__)
#define RB_FOREACH_61(WHAT, X, ...) WHAT(X)RB_FOREACH_60(WHAT, __VA_ARGS__)
#define RB_FOREACH_62(WHAT, X, ...) WHAT(X)RB_FOREACH_61(WHAT, __VA_ARGS__)
#define RB_FOREACH_63(WHAT, X, ...) WHAT(X)RB_FOREACH_62(WHAT, __VA_ARGS__)
#define RB_FOREACH_64(WHAT, X, ...) WHAT(X)RB_FOREACH_63(WHAT, __VA_ARGS__)

#define RB_GET_MACRO(\
    _0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,\
    _16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,\
    _32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,\
    _48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,\
    NAME,...) NAME

#define RB_FOR_EACH(action,...) \
  RB_GET_MACRO(_0,__VA_ARGS__, \
    RB_FOREACH_64, RB_FOREACH_63, RB_FOREACH_62, RB_FOREACH_61, RB_FOREACH_60,\
    RB_FOREACH_59, RB_FOREACH_58, RB_FOREACH_57, RB_FOREACH_56, RB_FOREACH_55,\
    RB_FOREACH_54, RB_FOREACH_53, RB_FOREACH_52, RB_FOREACH_51, RB_FOREACH_50,\
    RB_FOREACH_49, RB_FOREACH_48, RB_FOREACH_47, RB_FOREACH_46, RB_FOREACH_45,\
    RB_FOREACH_44, RB_FOREACH_43, RB_FOREACH_42, RB_FOREACH_41, RB_FOREACH_40,\
    RB_FOREACH_39, RB_FOREACH_38, RB_FOREACH_37, RB_FOREACH_36, RB_FOREACH_35,\
    RB_FOREACH_34, RB_FOREACH_33, RB_FOREACH_32, RB_FOREACH_31, RB_FOREACH_30,\
    RB_FOREACH_29, RB_FOREACH_28, RB_FOREACH_27, RB_FOREACH_26, RB_FOREACH_25,\
    RB_FOREACH_24, RB_FOREACH_23, RB_FOREACH_22, RB_FOREACH_21, RB_FOREACH_20,\
    RB_FOREACH_19, RB_FOREACH_18, RB_FOREACH_17, RB_FOREACH_16, RB_FOREACH_15,\
    RB_FOREACH_14, RB_FOREACH_13, RB_FOREACH_12, RB_FOREACH_11, RB_FOREACH_10,\
    RB_FOREACH_9, RB_FOREACH_8, RB_FOREACH_7, RB_FOREACH_6, RB_FOREACH_5,\
    RB_FOREACH_4, RB_FOREACH_3, RB_FOREACH_2, RB_FOREACH_1, RB_FOREACH_0 \
  )(action,__VA_ARGS__)

}
#endif

